# Generated by Django 6.0.2 on 2026-03-15 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=254)),
                ('cesPoints', models.IntegerField(default=0)),
                ('idNum', models.IntegerField(default=0)),
            ],
        ),
    ]
