# Generated by Django 6.0.2 on 2026-04-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leveledapikey',
            old_name='student',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='idNum',
            field=models.CharField(default='XXXXXXXXXXXXXXXXXXXXX', max_length=255),
        ),
    ]
